-- Missing tables for Unified Medical Platform
-- Run this in Supabase SQL Editor

-- Clinic Surgeries (scheduled surgeries from clinic, NOT the surgical logbook)
CREATE TABLE IF NOT EXISTS surgeries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    surgery_date TEXT NOT NULL,
    surgery_type TEXT NOT NULL,
    laterality TEXT,
    surgeon_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    assistant TEXT,
    anesthesia_type TEXT,
    preop_diagnosis TEXT,
    postop_diagnosis TEXT,
    approach TEXT,
    findings TEXT,
    closure TEXT,
    status TEXT DEFAULT 'Scheduled',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Surgery Implants
CREATE TABLE IF NOT EXISTS surgery_implants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surgery_id BIGINT NOT NULL REFERENCES surgeries(id) ON DELETE CASCADE,
    implant_name TEXT NOT NULL,
    manufacturer TEXT,
    size TEXT,
    lot_number TEXT,
    serial_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
