-- Unified Medical Platform: Supabase PostgreSQL Schema
-- Paste this script into the Supabase SQL Editor and click "Run".

-- 1. Users (Auth)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    full_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Hospitals (From Surgical Logbook)
CREATE TABLE hospitals (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT DEFAULT '',
    active INTEGER DEFAULT 1
);

-- 3. Patients (Unified)
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Core fields
    name TEXT NOT NULL,
    mrn TEXT, -- From Surgical Logbook
    dob TEXT,
    age INTEGER, -- Fallback if DOB is not provided
    gender TEXT, -- From Surgical Logbook
    phone TEXT,
    
    -- Medical History
    dm TEXT,
    htn TEXT,
    asthma TEXT,
    medications TEXT,
    allergies TEXT,
    surgeries TEXT,
    notes TEXT,
    chronic_diseases TEXT,
    
    -- Social / Ortho Details
    occupation TEXT,
    sports_level TEXT,
    smoking TEXT,
    injury_mechanism TEXT,
    laterality TEXT,
    
    -- Insurance
    insurance TEXT,
    is_insured INTEGER DEFAULT 0,
    insurance_policy_no TEXT,
    insurance_expiry TEXT,
    
    -- Emergency
    emergency_contact TEXT,
    
    -- System flags
    is_clinic_patient BOOLEAN DEFAULT TRUE, -- False for Fellowship-only cases
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Appointments
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
    patient_name TEXT NOT NULL,
    patient_phone TEXT,
    appointment_date TEXT NOT NULL,
    appointment_time TEXT,
    reason TEXT,
    status TEXT DEFAULT 'Scheduled',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Visits (Clinic)
CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    visit_date TEXT NOT NULL,
    reason TEXT,
    history TEXT,
    examination TEXT,
    
    -- Investigations
    labs TEXT,
    xray TEXT,
    ct TEXT,
    mri TEXT,
    us TEXT,
    imaging_other TEXT,
    
    -- Ortho specifics
    special_tests TEXT,
    neurovascular TEXT,
    injury_mechanism TEXT,
    
    -- Plan
    diagnosis TEXT,
    medications TEXT,
    procedures TEXT,
    followup TEXT,
    referrals TEXT,
    template_used TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Clinic Minor Procedures Log
CREATE TABLE procedures_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    procedure_date TEXT NOT NULL,
    procedure_type TEXT NOT NULL,
    body_part TEXT,
    laterality TEXT,
    medication_used TEXT,
    lot_number TEXT,
    volume_dose TEXT,
    consent_obtained INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Surgical Logbook Cases
CREATE TABLE surgical_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    
    case_date TEXT NOT NULL,
    hospital_code TEXT REFERENCES hospitals(code) ON DELETE SET NULL,
    specialty TEXT NOT NULL,
    
    diagnosis TEXT,
    findings TEXT,
    procedure TEXT NOT NULL,
    side TEXT,
    
    graft_type TEXT,
    implant TEXT,
    duration_min INTEGER,
    anaesthesia TEXT,
    complications TEXT,
    notes TEXT,
    
    role TEXT DEFAULT '',
    is_fellowship INTEGER DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. Surgical Logbook Follow-ups
CREATE TABLE surgical_followups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES surgical_cases(id) ON DELETE CASCADE,
    fu_date TEXT NOT NULL,
    notes TEXT,
    outcome TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. Clinic Follow-ups
CREATE TABLE clinic_followups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    -- If you want to link clinic surgeries later, you can add:
    -- clinic_surgery_id BIGINT REFERENCES clinic_surgeries(id) ON DELETE SET NULL,
    
    due_date TEXT NOT NULL,
    rehab_phase TEXT,
    vas_score INTEGER,
    rom_notes TEXT,
    outcome_score_type TEXT,
    outcome_score_value TEXT,
    status TEXT DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. Billing Invoices
CREATE TABLE billing_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    visit_id BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    invoice_date TEXT NOT NULL,
    total_amount REAL DEFAULT 0.0,
    discount REAL DEFAULT 0.0,
    net_amount REAL DEFAULT 0.0,
    status TEXT DEFAULT 'Unpaid',
    payment_method TEXT,
    insurance_company TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 11. Billing Items
CREATE TABLE billing_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    unit_price REAL DEFAULT 0.0,
    total_price REAL DEFAULT 0.0
);

-- 12. Payments
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
    payment_date TEXT NOT NULL,
    amount REAL NOT NULL,
    payment_method TEXT NOT NULL,
    reference_no TEXT,
    received_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 13. Expenses
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount REAL NOT NULL,
    payment_method TEXT,
    receipt_no TEXT,
    recorded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 14. Inventory
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    category TEXT,
    supplier TEXT,
    cost_price REAL DEFAULT 0.0,
    selling_price REAL DEFAULT 0.0,
    current_stock INTEGER DEFAULT 0,
    min_stock_alert INTEGER DEFAULT 5,
    expiry_date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 15. External Income
CREATE TABLE external_income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_date TEXT NOT NULL,
    source TEXT NOT NULL,
    description TEXT,
    amount REAL NOT NULL,
    recorded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
